# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designerView.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(519, 391)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonRock = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRock.setGeometry(QtCore.QRect(90, 110, 101, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonRock.setFont(font)
        self.buttonRock.setObjectName("buttonRock")
        self.buttonPaper = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPaper.setGeometry(QtCore.QRect(210, 110, 101, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonPaper.setFont(font)
        self.buttonPaper.setObjectName("buttonPaper")
        self.buttonScissors = QtWidgets.QPushButton(self.centralwidget)
        self.buttonScissors.setGeometry(QtCore.QRect(330, 110, 101, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonScissors.setFont(font)
        self.buttonScissors.setObjectName("buttonScissors")
        self.buttonLizard = QtWidgets.QPushButton(self.centralwidget)
        self.buttonLizard.setGeometry(QtCore.QRect(150, 210, 101, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonLizard.setFont(font)
        self.buttonLizard.setObjectName("buttonLizard")
        self.buttonSpock = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSpock.setGeometry(QtCore.QRect(270, 210, 101, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonSpock.setFont(font)
        self.buttonSpock.setObjectName("buttonSpock")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(140, 50, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonRock.setText(_translate("MainWindow", "Rock"))
        self.buttonPaper.setText(_translate("MainWindow", "Paper"))
        self.buttonScissors.setText(_translate("MainWindow", "Scissors"))
        self.buttonLizard.setText(_translate("MainWindow", "Lizard"))
        self.buttonSpock.setText(_translate("MainWindow", "Spock"))
        self.labelTitle.setText(_translate("MainWindow", "LET\'S PLAY A GAME!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
